repos:
  - repo: local
    hooks:
      - id: jupyter-nb-clear-output # from https://zhauniarovich.com/post/2020/2020-06-clearing-jupyter-output/
        name: jupyter-nb-clear-output
        files: \.ipynb$
        stages: [commit]
        language: system
        entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace
